//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting_entry
    {
        public accounting_entry()
        {
            this.accounting_entry_detail = new HashSet<accounting_entry_detail>();
        }
    
        public int id { get; set; }
        public int accounting_clerk_id { get; set; }
        public int currency_id { get; set; }
        public string description { get; set; }
        public int state { get; set; }
        public System.DateTime create_on { get; set; }
    
        public virtual accounting_clerk accounting_clerk { get; set; }
        public virtual currency currency { get; set; }
        public virtual ICollection<accounting_entry_detail> accounting_entry_detail { get; set; }
    }
}
