//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_type
    {
        public account_type()
        {
            this.account_catalog = new HashSet<account_catalog>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public bool state { get; set; }
    
        public virtual ICollection<account_catalog> account_catalog { get; set; }
    }
}
