//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_exchange
    {
        public int id { get; set; }
        public int currency_id { get; set; }
        public double amount { get; set; }
        public Nullable<System.DateTime> create_on { get; set; }
    
        public virtual currency currency { get; set; }
    }
}
