//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public currency()
        {
            this.accounting_entry = new HashSet<accounting_entry>();
            this.currency_exchange = new HashSet<currency_exchange>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public bool state { get; set; }
    
        public virtual ICollection<accounting_entry> accounting_entry { get; set; }
        public virtual ICollection<currency_exchange> currency_exchange { get; set; }
    }
}
