//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accounting_dbEntities : DbContext
    {
        public accounting_dbEntities()
            : base("name=accounting_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account_catalog> account_catalog { get; set; }
        public DbSet<account_type> account_type { get; set; }
        public DbSet<accounting_clerk> accounting_clerk { get; set; }
        public DbSet<accounting_entry> accounting_entry { get; set; }
        public DbSet<accounting_entry_detail> accounting_entry_detail { get; set; }
        public DbSet<currency> currency { get; set; }
        public DbSet<currency_exchange> currency_exchange { get; set; }
        public DbSet<user_accounting> user_accounting { get; set; }
    }
}
