//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_accounting
    {
        public string username { get; set; }
        public string fullname { get; set; }
        public string user_password { get; set; }
    }
}
